apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: upe1eaqq2-nodejs
  janus-idp.io/tekton: upe1eaqq2-nodejs
  backstage.io/kubernetes-id: upe1eaqq2-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: upe1eaqq2-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
